# Generated by Django 3.0.3 on 2020-02-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('company_mail', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=70)),
                ('salary', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('created_at', models.BooleanField(default=True)),
            ],
        ),
    ]
