# Generated by Django 3.0.3 on 2020-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='job_descirption',
            field=models.TextField(default=None),
        ),
    ]
