# Generated by Django 3.0.3 on 2020-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200226_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='available',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='created_at',
            field=models.BooleanField(default=True),
        ),
    ]
